services:
  nginx:
    build: "nginx"
    ports:
      - "5005:5000"
    links:
      - pass-through:pass-through
      - registry:registry
  pass-through:
    build:
      context: "../"
      dockerfile: pass-through.Dockerfile
    ports:
      - "5000"
    volumes:
      - ./cache:/var/lib/registry:rw
  registry:
    build:
      context: "../"
      dockerfile: registry.Dockerfile
    ports:
      - "5000"
    volumes:
      - ./cache:/var/lib/registry:rw